services:
  - type: web
    name: quickutil-pdf-api
    env: python
    buildCommand: |
      apt-get update && 
      apt-get install -y ghostscript && 
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 